function [html] = generate_html(method, type, image_rankings, mAP, AP, vocabulary_size, kernel, name)
    final_img_str = '';
    image_set_size = size(image_rankings{1},2);
    for j=1:4
        single_img_str = '';
        for i = 1:image_set_size
            image_cell = image_rankings{j}(i);
            img_name = strcat('../',image_cell{1});
            %imshow(img_name);
            single_img_str = strcat(single_img_str, sprintf('<td><img src=\"%s\"/></td>', img_name));
        end
        single_row_str = sprintf('<tr>%s</tr>', single_img_str);
        final_img_str = strcat(final_img_str, single_row_str);
    end
   

    final_html = ['<!DOCTYPE html>'...
        '<html lang="en">'...
        '<head>'...
        '<meta charset="utf-8">'...
        '<title>Image list prediction</title>'...
        '<style type="text/css">'...
        'img {'...
        'width:200px;'...
        '}'...
        '</style>'...
        '</head>'...
        '<body>'...
        '<h2>Basak Eskili, Lukas Jelinek</h2>'...
        '<h1>Settings</h1>'...
        '<table>'...
        sprintf('<tr><th>SIFT features</th><td>%s</td></tr>%s', type)...
        sprintf('<tr><th>SIFT method</th><td>%s-SIFT</td></tr>', method)...
        sprintf('<tr><th>Vocabulary size</th><td>%d words</td></tr>', vocabulary_size)...
        sprintf('<tr><th>SVM kernel type</th><td>%s</td></tr>', kernel)...
        '</table>'...
        sprintf('<h1>Prediction lists (MAP: %f)</h1>', mAP)...
        '<table>'...
        '<thead>'...
        '<tr>'...
        sprintf('<th>Airplanes (AP: %f)</th>', AP(1))...
        sprintf('<th>Cars (AP: %f)</th>', AP(2))...
        sprintf('<th>Faces (AP: %f)</th>', AP(3))...
        sprintf('<th>Motorbikes (AP: %f)</th>', AP(4))...
        '</tr>'...
        '</thead>'...
        sprintf('<tbody>%s', final_img_str)...
        '</tbody>'...
        '</table>'...
        '</body>'...
        '</html>'
    ];
    html = string(final_html);
    fid=fopen(strcat('html_pages/',name,'.html'),'w');

    fprintf(fid, html);
    fclose(fid);
    
end